// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdxkTeSEgTneVijqXjmO5g29VNQjIChRc',
    appId: '1:351066335763:web:1114a4d760f1e94ce32de6',
    messagingSenderId: '351066335763',
    projectId: 'rowanrasid',
    authDomain: 'rowanrasid.firebaseapp.com',
    storageBucket: 'rowanrasid.firebasestorage.app',
    measurementId: 'G-4W33Q2ZHM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3IIRpxHlYZCpD_0gVNcGtK56xyob5eo0',
    appId: '1:351066335763:android:f29b4235c1012eefe32de6',
    messagingSenderId: '351066335763',
    projectId: 'rowanrasid',
    storageBucket: 'rowanrasid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbYGQzNxuDZmE_vliPQ0SCd4eBS4RYaKA',
    appId: '1:351066335763:ios:c95bddbc116a6f16e32de6',
    messagingSenderId: '351066335763',
    projectId: 'rowanrasid',
    storageBucket: 'rowanrasid.firebasestorage.app',
    iosBundleId: 'com.example.rowanrasid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbYGQzNxuDZmE_vliPQ0SCd4eBS4RYaKA',
    appId: '1:351066335763:ios:c95bddbc116a6f16e32de6',
    messagingSenderId: '351066335763',
    projectId: 'rowanrasid',
    storageBucket: 'rowanrasid.firebasestorage.app',
    iosBundleId: 'com.example.rowanrasid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdxkTeSEgTneVijqXjmO5g29VNQjIChRc',
    appId: '1:351066335763:web:ec6f600d004a2cf9e32de6',
    messagingSenderId: '351066335763',
    projectId: 'rowanrasid',
    authDomain: 'rowanrasid.firebaseapp.com',
    storageBucket: 'rowanrasid.firebasestorage.app',
    measurementId: 'G-ZSPGFYW5LP',
  );
}
